sudo: required
services:
  - docker

before_install:
  - docker build -t daylanberry/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true daylanberry/react-test npm test -- --coverage

after_success:
  - docker build -t daylanberry/multi-client ./client
  - docker build -t daylanberry/multi-nginx ./nginx
  - docker build -t daylanberry/multi-server ./server
  - docker build -t daylanberry/multi-worker ./worker

  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take images and push to docker hub
  - docker push daylanberry/multi-client
  - docker push daylanberry/multi-nginx
  - docker push daylanberry/multi-server
  - docker push daylanberry/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-449009677396"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
